version: "3.4"

services:
  symfony-grpc:
    build:
      context: .
      dockerfile: Dockerfile
      target: symfony-grpc
    container_name: symfony-grpc
    ports:
      - "80:80"
    volumes:
      - ./symfony-grpc/:/app/symfony:rw,cached
    depends_on:
      - phprom-grpc

  symfony-rest:
    build:
      context: .
      dockerfile: Dockerfile
      target: symfony-rest
    container_name: symfony-rest
    ports:
      - "8080:8080"
    volumes:
      - ./symfony-rest:/app/symfony:rw,cached
    depends_on:
      - phprom-rest

  phprom-grpc:
    image: chaseisabelle/phprom:latest
    container_name: phprom-grpc
    ports:
      - "3333:3333"

  phprom-rest:
    image: chaseisabelle/phprom:latest
    container_name: phprom-rest
    command: /phprom --address=0.0.0.0:8888 --api=rest
    ports:
      - "8888:8888"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - type: bind
        source: ./prometheus.yaml
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - symfony-grpc
      - symfony-rest

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus


