version: "3.4"

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony
    ports:
      - "80:80"
    volumes:
      - ./:/app:rw,cached

  phprom:
    image: chaseisabelle/phprom:latest
    container_name: phprom
    ports:
      - "3333:3333"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - type: bind
        source: ./prometheus.yaml
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - phprom

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus


