version: "3.4"

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony
    ports:
      - "80:80"
    volumes:
      - ./:/app:rw,cached

  phprom:
    image: chaseisabelle/phprom:latest
    container_name: phprom
    ports:
      - "3333:3333"

